[package]
name = "linux-ai-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Command line for Linux AI."
keywords = ["ai", "llm", "cli", "assistant", "linux"]
categories = ["command-line-utilities"]

[[bin]]
name = "lai"
path = "src/main.rs"

[dependencies]
la-core = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
clap = { workspace = true }
rustyline = "18"
anyhow = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
tracing-subscriber = { workspace = true }
