[package]
name = "linux-ai-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Desktop app for Linux AI."

[lib]
name = "linux_ai_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "linux-ai-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
la-core = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
cpal = "0.17"
hound = "3"
